# Generated by Django 5.0.4 on 2024-05-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='image',
            new_name='imagen',
        ),
    ]
